### ISSUE TITLE
0.3.0 release checklist

### ISSUE THREAD

**Issue by yallop** [dsheets/ocaml-unix-unistd#15]
* [x] Add a more detailed [README][README] (#16)
* [x] Review the interface for consistency and completeness
* [x] Bring the authors list up to date
* [x] Update the [changelog][changelog]
* [x] Check the build with and without optional dependencies
* [x] Update version numbers
* [x] Tag
* [x] Publish on [opam-repository][opam-repository]

[README]: https://github.com/dsheets/ocaml-unix-unistd/blob/master/README.md
[changelog]: https://github.com/dsheets/ocaml-unix-unistd/blob/master/CHANGES
[opam-repository]: https://github.com/ocaml/opam-repository/

**Comment by dsheets** [comment]
Also, checking whether we've cleared #7, #8, and #11 would be useful.

**Comment by yallop** [comment]
https://github.com/ocaml/opam-repository/pull/7494
